# Generated by Django 4.2.1 on 2026-03-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название места')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('area', models.CharField(max_length=120, verbose_name='Район')),
                ('area_slug', models.SlugField(max_length=120)),
                ('noise_level', models.PositiveSmallIntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=2, verbose_name='Уровень шума')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], db_index=True, default=1, verbose_name='Статус публикации')),
            ],
            options={
                'verbose_name': 'Тихое место',
                'verbose_name_plural': 'Тихие места',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='spots_spot_time_cr_bcdae9_idx'), models.Index(fields=['status'], name='spots_spot_status_830116_idx'), models.Index(fields=['area_slug'], name='spots_spot_area_sl_5d5916_idx')],
            },
        ),
    ]
