# Generated by Codex on 2026-03-20

from django.db import migrations


def seed_spots(apps, schema_editor):
    Spot = apps.get_model("spots", "Spot")
    seed_rows = [
        {
            "title": "Читальный зал у воды",
            "slug": "chitalny-zal-u-vody",
            "content": "Тихая зона с видом на реку и стабильным Wi-Fi.",
            "area": "Набережная",
            "area_slug": "naberezhnaya",
            "noise_level": 1,
            "status": 1,
        },
        {
            "title": "Сквер сосновый",
            "slug": "skver-sosnovyy",
            "content": "Мало людей утром, есть скамейки и тень от деревьев.",
            "area": "Заельцовский",
            "area_slug": "zaeltsovskiy",
            "noise_level": 2,
            "status": 1,
        },
        {
            "title": "Коворкинг на Красном",
            "slug": "kovorking-na-krasnom",
            "content": "Подходит для коротких задач, но в обед бывает шумно.",
            "area": "Центр",
            "area_slug": "center",
            "noise_level": 3,
            "status": 1,
        },
    ]
    for row in seed_rows:
        Spot.objects.update_or_create(slug=row["slug"], defaults=row)


def clear_spots(apps, schema_editor):
    Spot = apps.get_model("spots", "Spot")
    Spot.objects.filter(
        slug__in=[
            "chitalny-zal-u-vody",
            "skver-sosnovyy",
            "kovorking-na-krasnom",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_spots, clear_spots),
    ]
