# Generated by Django 4.2.1 on 2026-05-14 14:56

from django.db import migrations, models
import spots.uploads


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_lab8_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=spots.uploads.spot_photo_upload_to, verbose_name='Фотография'),
        ),
    ]
